### ISSUE TITLE
bjump-help-link-jump fails in certain describe-variable buffers 

### ISSUE THREAD

**Issue by glucas** [Fuco1/better-jump#2]
When a Help buffer describing a variable includes a link to the value elsewhere in the buffer ("below"), I get the following error trying to use bjump-help-link-jump.

For example, describe-variable auto-mode-alist and then jump gives this: 

```
and: Wrong type argument: number-or-marker-p, #<overlay from 73 to 78 in *Help*>
```

I'm on Emacs 24.4.

**Comment by Fuco1** [comment]
Thanks for the report.  I was able to replicate the issue and I pushed a fix.  Sorry it took me 10 years :blush: :man_facepalming:
