### ISSUE TITLE
Extra letter needed when number of choices == number of letters

### ISSUE THREAD

**Issue by glucas** [Fuco1/better-jump#3]
When calling bjump-word-jump and the number of possible single letters happens to be equal to the number of possible jump targets, all the targets get labeled with the same letter (e.g. 'a').

Tweaking `bjump-picker-single-letter` to increment the num-choices here fixes it for me:

```
(floor (log num-selected (+ 1 num-choices)))
```

**Comment by Fuco1** [comment]
You're right, I applied your fix. Thanks!
